<?php
/**
 * Path Configuration for LeaveTracker
 * Auto-generated by fix_paths_comprehensive.php
 */

// Define project root
define("PROJECT_ROOT", __DIR__);

// Function to get correct path based on current location
function getPath($target) {
    $currentDir = dirname($_SERVER["SCRIPT_FILENAME"]);
    $projectRoot = PROJECT_ROOT;
    
    // Calculate relative path
    $relativePath = "";
    $currentParts = explode(DIRECTORY_SEPARATOR, $currentDir);
    $rootParts = explode(DIRECTORY_SEPARATOR, $projectRoot);
    
    // Find how many levels up we need to go
    $levelsUp = count($currentParts) - count($rootParts);
    
    for ($i = 0; $i < $levelsUp; $i++) {
        $relativePath .= "../";
    }
    
    return $relativePath . $target;
}

// Common path constants
define("CONFIG_PATH", getPath("config"));
define("INCLUDES_PATH", getPath("includes"));
define("MODULES_PATH", getPath("modules"));
define("ADMIN_PATH", getPath("admin"));
define("DASHBOARDS_PATH", getPath("dashboards"));
define("REPORTS_PATH", getPath("reports"));
define("AUTH_PATH", getPath("auth"));
define("CSS_PATH", getPath("css"));
define("JS_PATH", getPath("js"));
define("IMAGES_PATH", getPath("images"));
define("UPLOADS_PATH", getPath("uploads"));
define("CLASSES_PATH", getPath("classes"));
?>